<?php

class IndexControlador{

    public function homeGerente(){return 'app/vistas/homegerente/index.php';}
    //-----------------------------------------------------------------------------------------
    public function politicaRuta(){return 'app/vistas/sasisopa/elemento1/politica-index.php';}
    public function descargarPolitica(){return 'app/vistas/sasisopa/elemento1/descargar-politica.php';}
    public function descargarListaComprobacion(){return 'app/vistas/sasisopa/elemento1/descargar-lista-comprobacion.php';}
    public function descargarListaAsistencia(){return 'app/vistas/sasisopa/asistencia/descargar-lista-asistencia.php';}
    public function listaAsistencia(){return 'app/vistas/sasisopa/asistencia/lista-asistencia-index.php';}
    public function analisisRiesgoEvaluacionImpactosAmbientales(){return 'app/vistas/sasisopa/elemento2/analisis-riesgo-evaluacion-impactos-ambientales-index.php';}
    public function descargarFormato2(){return 'app/vistas/sasisopa/elemento2/descargar-formato-2.php';}
    public function descargarFormato3(){return 'app/vistas/sasisopa/elemento2/descargar-formato-3.php';}
    public function requisitosLegales(){return 'app/vistas/sasisopa/elemento3/requisitos-legales-index.php';}
    public function requisitosLegalesConfiguracion(){return 'app/vistas/sasisopa/elemento3/requisitos-legales-configuracion-index.php';}
    public function descargarRequisitosLegales(){return 'app/vistas/sasisopa/elemento3/descargar-requisitos-legales.php';}
    public function detalleRequisitosLegales(){return 'app/vistas/sasisopa/elemento3/detalle-requisitos-legales-index.php';}
    public function objetivosMetasIndicadores(){return 'app/vistas/sasisopa/elemento4/objetivos-metas-indicadores.php';}
    public function capacitacionPersonal(){return 'app/vistas/sasisopa/elemento4/capacitacion-personal-index.php';}
    public function experienciaCliente(){return 'app/vistas/sasisopa/elemento4/experiencia-cliente-index.php';}
    public function agregarExperienciaCliente(){return 'app/vistas/sasisopa/elemento4/agregar-experiencia-cliente-index.php';}
    public function detalleExperienciaCliente(){return 'app/vistas/sasisopa/elemento4/detalle-experiencia-cliente-index.php';}
    public function editarExperienciaCliente(){return 'app/vistas/sasisopa/elemento4/editar-experiencia-cliente-index.php';}
    public function indicadorVentas(){return 'app/vistas/sasisopa/elemento4/indicador-ventas-index.php';}
    public function indicadorVentasReporte(){return 'app/vistas/sasisopa/elemento4/indicador-ventas-reporte-index.php';}
    public function funcionesResponsabilidadesAutoridad(){return 'app/vistas/sasisopa/elemento5/funciones-responsabilidades-autoridad.php';}
    public function competenciaPersonalCapacitacionEntrenamiento(){return 'app/vistas/sasisopa/elemento6/competencia-personal-capacitacion-entrenamiento.php';}
    public function perfilesPuestoTrabajo(){return 'app/vistas/sasisopa/elemento6/perfiles-puesto-index.php';}
    public function perfilesPersonal(){return 'app/vistas/sasisopa/elemento6/perfiles-personal-index.php';}
    public function descargarFichaPersonal(){return 'app/vistas/sasisopa/elemento6/descargar-ficha-personal.php';}
    public function descargarFichaPersonalReporte(){return 'app/vistas/sasisopa/elemento6/descargar-ficha-personal-reporte.php';}
    public function fichaPersonal(){return 'app/vistas/sasisopa/elemento6/ficha-personal-index.php';}
    public function capacitacionInterna(){return 'app/vistas/sasisopa/elemento6/capacitacion-interna-index.php';}
    public function capacitacionInternaModulos(){return 'app/vistas/sasisopa/elemento6/capacitacion-interna-modulos-index.php';}
    public function capacitacionExterna(){return 'app/vistas/sasisopa/elemento6/capacitacion-externa-index.php';}
    public function descargarCapacitacionExterna(){return 'app/vistas/sasisopa/elemento6/descargar-capacitacion-externa.php';}
    public function comunicacionParticipacionConsulta(){return 'app/vistas/sasisopa/elemento7/comunicacion-participacion-consulta-index.php';}
    public function descargarComunicacionParticipacionConsulta(){return 'app/vistas/sasisopa/elemento7/descargar-comunicacion-participacion-consulta.php';}
    public function descargarComunicacionParticipacionConsultaReporte(){return 'app/vistas/sasisopa/elemento7/descargar-comunicacion-participacion-consulta-reporte.php';}
    public function descargarQuejaSugerencia(){return 'app/vistas/sasisopa/elemento7/descargar-quejas-sugerencias.php';}
    public function controlDocumentosRegistros(){return 'app/vistas/sasisopa/elemento8/control-documentos-registros-index.php';}
    public function controlDocumentosRL(){return 'app/vistas/sasisopa/elemento8/control-documentos-rl-index.php';}
    public function descargarControlDocumentosRL(){return 'app/vistas/sasisopa/elemento8/descargar-control-documentos-rl.php';}
    public function controlDocumentosSA(){return 'app/vistas/sasisopa/elemento8/control-documentos-sa-index.php';}
    public function descargarControlDocumentosSA(){return 'app/vistas/sasisopa/elemento8/descargar-control-documentos-sa.php';}
    public function mejoresPracticasEstandares(){return 'app/vistas/sasisopa/elemento9/mejores-practicas-estandares-index.php';}
    public function descargarDisenoConstruccion(){return 'app/vistas/sasisopa/elemento9/descargar-diseno-construccion.php';}
    public function descargarOperacionMantenimiento(){return 'app/vistas/sasisopa/elemento9/descargar-operacion-mantenimiento.php';}
    public function controlActividadesProcesos(){return 'app/vistas/sasisopa/elemento10/control-actividades-procesos-index.php';}
    public function programaAnualMantenimiento(){return 'app/vistas/sasisopa/elemento10/programa-anual-mantenimiento-index.php';}
    public function agregarProgramaAnual(){return 'app/vistas/sasisopa/elemento10/agregar-programa-anual-index.php';}
    public function descargarProgramaAnualMantenimiento(){return 'app/vistas/sasisopa/elemento10/descargar-programa-anual-mantenimiento.php';}
    public function configuracionBitacora(){return 'app/vistas/sasisopa/elemento10/configuracion-bitacora-index.php';}
    public function recepcionDescargarProducto(){return 'app/vistas/sasisopa/elemento10/recepcion-descargar-producto-index.php';}
    public function mantenimientoPreventivoCorrectivo(){return 'app/vistas/sasisopa/elemento10/mantenimiento-preventivo-correctivo-index.php';}
    public function descargarReporteMantenimientoPreventivo(){return 'app/vistas/sasisopa/elemento10/descargar-reporte-mantenimiento-preventivo.php';}
    public function configuracionExtintores(){return 'app/vistas/sasisopa/elemento10/configuracion-extintores-index.php';}
    public function configuracionDetectorHumo(){return 'app/vistas/sasisopa/elemento10/configuracion-detector-humo-index.php';}
    public function mantenimientoCorrectivo(){return 'app/vistas/sasisopa/elemento10/mantenimiento-correctivo-index.php';}
    public function reporteMantenimientoCorrectivo(){return 'app/vistas/sasisopa/elemento10/reporte-mantenimiento-correctivo-index.php';}
    public function calibracionEquipos(){return 'app/vistas/sasisopa/elemento10/calibracion-equipos-index.php';}
    public function configuracionTanques(){return 'app/vistas/sasisopa/elemento10/configuracion-tanques-index.php';}
    public function configuracionDispensario(){return 'app/vistas/sasisopa/elemento10/configuracion-dispensario-index.php';}
    public function configuracionSondasMedicion(){return 'app/vistas/sasisopa/elemento10/configuracion-sondas-medicion-index.php';}
    public function configuracionJarraPatron(){return 'app/vistas/sasisopa/elemento10/configuracion-jarra-patron-index.php';}
    public function bitacoraCalibracionEquipos(){return 'app/vistas/sasisopa/elemento10/bitacora-calibracion-equipos-index.php';}
    public function bitacoraCalibracionEquipoJarraPatron(){return 'app/vistas/sasisopa/elemento10/bitacora-calibracion-equipos-jarra-patron.php';}
    public function bitacoraCalibracionEquipoDispensario(){return 'app/vistas/sasisopa/elemento10/bitacora-calibracion-equipos-dispensario.php';}
    public function bitacoraCalibracionEquipoSonda(){return 'app/vistas/sasisopa/elemento10/bitacora-calibracion-equipos-sonda.php';}
    public function bitacoraCalibracionEquipoTanque(){return 'app/vistas/sasisopa/elemento10/bitacora-calibracion-equipos-tanques-almacenamiento.php';}
    public function descargarBitacoraCalibracionEquipo(){return 'app/vistas/sasisopa/elemento10/descargar-bitacora-calibracion-equipos.php';}
    public function bitacoraProfeco(){return 'app/vistas/sasisopa/elemento10/bitacora-profeco-index.php';}
    public function bitacoraDispensario(){return 'app/vistas/sasisopa/elemento10/bitacora-dispensario-index.php';}
    public function bitacoraMantenimiento(){return 'app/vistas/sasisopa/elemento10/bitacora-mantenimiento-index.php';}
    public function bitacoraMantenimientoQuincenal(){return 'app/vistas/sasisopa/elemento10/bitacora-mantenimiento-quincenal-index.php';}
    public function integridadMecanicaAseguramiento(){return 'app/vistas/sasisopa/elemento11/integridad-mecanica-aseguramiento-index.php';}
    public function bitacorasCaracteristicas(){return 'app/vistas/sasisopa/elemento11/bitacoras-caracteristicas-index.php';}
    public function descargarEquipoCritico(){return 'app/vistas/sasisopa/elemento11/descargar-equipos-criticos.php';}
    public function seguridadContratistas(){return 'app/vistas/sasisopa/elemento12/seguridad-contratistas-index.php';}
    public function descargarCartaResponsiva(){return 'app/vistas/sasisopa/elemento12/descargar-carta-responsiva.php';}
    public function descargarListaVerificacion(){return 'app/vistas/sasisopa/elemento12/descargar-lista-verificacion.php';}
    public function descargarAutorizacionTrabajosPeligrosos(){return 'app/vistas/sasisopa/elemento12/descargar-autorizacion-trabajos-peligrosos.php';}
    public function descargarSeguridadContratista(){return 'app/vistas/sasisopa/elemento12/descargar-seguridad-contratistas.php';}
    public function preparacionEmergencias(){return 'app/vistas/sasisopa/elemento13/preparacion-emergencias-index.php';}
    public function descargarSimulacros(){return 'app/vistas/sasisopa/elemento13/descargar-simulacros.php';}
    public function monitoreoVerificacionEvaluacion(){return 'app/vistas/sasisopa/elemento14/monitoreo-verificacion-evaluacion-index.php';}
    public function implementacionSA(){return 'app/vistas/sasisopa/elemento14/implementacion-sa-index.php';}
    public function ventasMes(){return 'app/vistas/sasisopa/elemento14/ventas-mes-index.php';}
    public function descargarRevisionResultadoDetalle(){return 'app/vistas/sasisopa/elemento14/descargar-revision-resultados-detalle.php';}
    public function descargarProgramaImplementacionSA(){return 'app/vistas/sasisopa/elemento14/descargar-programa-implementacion-s-a.php';}
    public function calibracionVerificacionMantenimientoEquipos(){return 'app/vistas/sasisopa/elemento14/calibracion-verificacion-mantenimiento-equipos.php';}
    public function descargarEquipoSometidosCalibracion(){return 'app/vistas/sasisopa/elemento14/descargar-equipos-sometidos-calibracion.php';}
    public function descargarCalendarioCalibracion(){return 'app/vistas/sasisopa/elemento14/descargar-calendario-calibracion.php';}
    public function evaluacionCumplimientoRequisitosLegales(){return 'app/vistas/sasisopa/elemento14/evaluacion-cumplimiento-requisitos-legales-index.php';}
    public function descargarEvaluacionCumplimiento(){return 'app/vistas/sasisopa/elemento14/descargar-evaluacion-cumplimiento-legal.php';}
    public function atencionHallazgos(){return 'app/vistas/sasisopa/elemento14/atencion-hallazgos-index.php';}
    public function atencionHallazgosEditar(){return 'app/vistas/sasisopa/elemento14/atencion-hallazgos-editar.php';}
    public function descargarAtencionHallazgos(){return 'app/vistas/sasisopa/elemento14/descargar-atencion-hallazgos.php';}
    public function auditoria(){return 'app/vistas/sasisopa/elemento15/auditorias-index.php';}
    public function programaAuditoriaInternaExterna(){return 'app/vistas/sasisopa/elemento15/programa-auditorias-internas-externas-index.php';}
    public function descargarProgramaAuditoriaInternaExterna(){return 'app/vistas/sasisopa/elemento15/descargar-programa-auditorias-internas-externas.php';}
    public function auditoriaInterna(){return 'app/vistas/sasisopa/elemento15/auditoria-interna-index.php';}
    public function auditoriaExterna(){return 'app/vistas/sasisopa/elemento15/auditoria-externa-index.php';}
    public function investigacionIncidentesAccidentes(){return 'app/vistas/sasisopa/elemento16/investigacion-incidentes-accidentes-index.php';}
    public function descargarIncidentesAccidentes(){return 'app/vistas/sasisopa/elemento16/descargar-investigacion-incidentes-accidentes.php';}
    public function descargarSinIncidentesAccidentes(){return 'app/vistas/sasisopa/elemento16/descargar-investigacion-sin-incidentes-accidentes.php';}
    public function revisionResultados(){return 'app/vistas/sasisopa/elemento17/revision-resultados-index.php';}
    public function informeDesempeno(){return 'app/vistas/sasisopa/elemento18/informes-desempeno-index.php';}
    public function descargarRegistroAtencionSeguimiento(){return 'app/vistas/sasisopa/elemento18/descargar-registro-atencio-seguimiento-comunicacion-interna-externa.php';}
    public function detalleImplementacionSasisopa(){return 'app/vistas/sasisopa/elemento18/detalle-implementacion-sasisopa-index.php';}
    //----------------------------------------------------------------------------------------------------------------------------------------------
    public function nom035Etapas(){return 'app/vistas/nom035/nom-035-etapas-index.php';}
    public function nom035Politica(){return 'app/vistas/nom035/nom-035-politica-index.php';}
    public function nom035Acontecimientos(){return 'app/vistas/nom035/nom-035-acontecimientos-index.php';}
    public function nom035FactoresRiesgo(){return 'app/vistas/nom035/nom-035-factores-riesgo-index.php';}
    //------------------------------------------------------------------------------------------------------------------------------------------------
    public function sgmIndex(){return 'app/vistas/sgm/index.php';}
    public function estructuraSistemaMedicion(){return 'app/vistas/sgm/punto1/index.php';}
    public function descargarListaAsistenciaSgm(){return 'app/vistas/sgm/lista-asistencia/descargar-lista-asistencia-sgm.php';}
    public function revisionSgmProcedimientoRegistro(){return 'app/vistas/sgm/revision-sgm-procedimientos-registros/revision-sgm-pocedimiento-registro.php';}
    public function descargarRevisionSgmProcedimientoRegistro(){return 'app/vistas/sgm/revision-sgm-procedimientos-registros/descargar-revision-sgm-pocedimiento-registro.php';}
    public function controlDocumentalSistemaGestionMedicion(){return 'app/vistas/sgm/punto2/index.php';}
    public function descargarControlDocumentalSgm(){return 'app/vistas/sgm/punto2/descargar-control-documental-sgm.php';}
    public function responsabilidadesDireccion(){return 'app/vistas/sgm/punto3/index.php';}
    public function editarPoliticaSgm(){return 'app/vistas/sgm/punto3/editar-politica-sgm.php';}
    public function establecimientoObjetivosEnfocadosCliente(){return 'app/vistas/sgm/punto4/index.php';}
    public function seguimientoObjetivosIndicadores(){return 'app/vistas/sgm/punto4/seguimiento-objetivos-indicadores.php';}
    public function descargarSeguimientoObjetivosIndicadores(){return 'app/vistas/sgm/punto4/descargar-seguimiento-objetivos-indicadores.php';}
    public function normatividadAplicableMediciones(){return 'app/vistas/sgm/punto5/index.php';}
    public function descargarInventarioNormatividadAplicable(){return 'app/vistas/sgm/punto5/descargar-inventario-normatividad-aplicable.php';}
    public function requisitosLegalesSgm(){return 'app/vistas/sgm/punto5/requisitos-legales-sgm.php';}
    public function descargarRequisitosLegalSgm(){return 'app/vistas/sgm/punto5/descargar-requisitos-legal-sgm.php';}
    public function gestionRecursos(){return 'app/vistas/sgm/punto6/index.php';}
    public function descargarResponsableSgm(){return 'app/vistas/sgm/punto6/descargar-responsable-sgm.php';}
    public function listaPersonalSgm(){return 'app/vistas/sgm/punto6/lista-personal-sgm.php';}
    public function descargarListaPersonalSgm(){return 'app/vistas/sgm/punto6/descargar-lista-personal-sgm.php';}
    public function inventarioEquipoSgm(){return 'app/vistas/sgm/punto6/inventario-equipo-sgm.php';}
    public function descargarInventarioEquipoSgm(){return 'app/vistas/sgm/punto6/descargar-inventario-equipo-sgm.php';}
    public function evaluacionProveedorServicioSgm(){return 'app/vistas/sgm/punto6/evaluacion-proveedor-servicio-sgm.php';}
    public function descargarOrdenServicioSgm(){return 'app/vistas/sgm/punto6/descargar-orden-servicio-sgm.php';}
    public function descargarEvaluacionProveedoresSgm(){return 'app/vistas/sgm/punto6/descargar-evaluacion-proveedores-sgm.php';}
    public function capacitacionInternaSgm(){return 'app/vistas/sgm/punto6/capacitacion-interna-sgm.php';}
    public function descargarProgramaAnualCapacitacionInternaSgm(){return 'app/vistas/sgm/punto6/descargar-programa-anual-capacitacion-interna-sgm.php';}
    public function descargarReconocimientoSgm(){return 'public/cursos/descargar-reconocimiento-sgm.php';}
    public function capacitacionExternaSgm(){return 'app/vistas/sgm/punto6/capacitacion-externa-sgm.php';}
    public function descargarProgramaAnualCapacitacionExternaSgm(){return 'app/vistas/sgm/punto6/descargar-programa-anual-capacitacion-externa-sgm.php';}
    public function capacitacionInduccionSgm(){return 'app/vistas/sgm/punto6/capacitacion-induccion-sgm.php';}
    public function descargarCapacitacionInduccionSgm(){return 'app/vistas/sgm/punto6/descargar-capacitacion-induccion-sgm.php';}

    public function procesosMedicion(){return 'app/vistas/sgm/punto7/index.php';}
    public function programaAnualCalibracionPatronesInstrumentosMedida(){return 'app/vistas/sgm/punto7/programa-anual-calibracion-patrones-instrumentos-medida.php';}
    public function descargarProgramaAnualSgm(){return 'app/vistas/sgm/punto7/descargar-programa-anual-sgm.php';}
    public function bitacoraCalibracionEquiposSgm(){return 'app/vistas/sgm/punto7/bitacora-calibracion-equipos-sgm.php';}
    public function bitacoraCalibracionEquiposSgmEditar(){return 'app/vistas/sgm/punto7/bitacora-calibracion-equipos-sgm-editar.php';}
    public function descargarBitacoraCalibracionEquiposSgm(){return 'app/vistas/sgm/punto7/descargar-bitacora-calibracion-equipos-sgm.php';}
    public function programaAnualVerificacionEquipos(){return 'app/vistas/sgm/punto7/programa-anual-verificacion-equipos.php';}
    public function bitacoraVerificacionEquipoMedicionSgm(){return 'app/vistas/sgm/punto7/bitacora-verificacion-equipo-medicion-sgm.php';}
    public function bitacoraVerificacionEquipoMedicionSgmEditar(){return 'app/vistas/sgm/punto7/bitacora-verificacion-equipo-medicion-sgm-editar.php';}
    public function descargarBitacoraVerificacionEquiposSgm(){return 'app/vistas/sgm/punto7/descargar-bitacora-verificacion-equipos-sgm.php';}

    public function gestionRiesgosImpactanMedicion(){return 'app/vistas/sgm/punto8/index.php';}
    public function establecimientoSeguimientoConfirmacionMetrologica(){return 'app/vistas/sgm/punto9/index.php';}
    public function auditoriasInternasExternasAtencionHallazgos(){return 'app/vistas/sgm/punto10/index.php';}
    public function planAuditoriaSgm(){return 'app/vistas/sgm/punto10/plan-auditoria-sgm.php';}
    public function descargarPlanAuditoriaSgm(){return 'app/vistas/sgm/punto10/descargar-plan-auditoria-sgm.php';}
    public function reporteHallazgosAuditoriaSgm(){return 'app/vistas/sgm/punto10/reporte-hallazgos-auditoria-sgm.php';}
    public function descargarReporteHallazgosAuditoriaSgm(){return 'app/vistas/sgm/punto10/descargar-reporte-hallazgos-auditoria-sgm.php';}
    public function planAtencionHallazgosSgm(){return 'app/vistas/sgm/punto10/plan-atencion-hallazgos-sgm.php';}
    public function descargarPlanAtencionHallazgosSgm(){return 'app/vistas/sgm/punto10/descargar-plan-atencion-hallazgos-sgm.php';}
    public function evaluacionCumplimientoObjetivosRevisionDireccion(){return 'app/vistas/sgm/punto11/index.php';}
    public function descargarEvaluacionCumplimientoSgm(){return 'app/vistas/sgm/punto11/descargar-evaluacion-cumplimiento-sgm.php';}
    
}
